splash = false

wallpaper {
	monitor = DP-3
	path = ~/Pictures/wallpapers/wallpaper1.png
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/wallpapers/wallpaper2.png
	fit_mode = cover
}
